name = "workers-airtable-form"
type = "javascript"

account_id = "keyjCOjMMrw7hA13R"
workers_dev = true


[vars]
AIRTABLE_BASE_ID = "tblLNDX7dDnOTZYy0"
AIRTABLE_TABLE_NAME = "test_project"
FORM_URL = "https://airtable.com/invite/r/reaVwXjP"
