name = "workers-airtable-form"
type = "javascript"

account_id = "z22mAd6d2i5N0Q9tiP8vJxNh0hBAv-NzPXm8S_Tv"
workers_dev = true


[vars]
AIRTABLE_BASE_ID = "appBFHpeTcmjrOC8e"
AIRTABLE_TABLE_NAME = "Project tracker"
FORM_URL = "https://api.airtable.com/v0/meta/bases"
