name = "workers-airtable-form"
type = "javascript"

account_id = "m4XhsHQMePB0PPoiOavF-pCVJ3AARiYyVB7m6zq9"
workers_dev = true


[vars]
AIRTABLE_BASE_ID = "keyjCOjMMrw7hA13R"
AIRTABLE_TABLE_NAME = "test_project"
FORM_URL = "https://airtable.com/invite/r/reaVwXjP"
