name = "workers-airtable-form"
type = "javascript"

account_id = "z22mAd6d2i5N0Q9tiP8vJxNh0hBAv-NzPXm8S_Tv"
workers_dev = true


[vars]
AIRTABLE_BASE_ID = "appWf2pM6T9WJnVEr"
AIRTABLE_TABLE_NAME = "test_project"
FORM_URL = "https://api.airtable.com/v0/appWf2pM6T9WJnVEr/Tasks?maxRecords=3&view=Grid%20view"
