name = "workers-airtable-form"
type = "javascript"

account_id = "RnLNDrpFW25FaPO0KGUS7-8_kylRwNX8Mg8W3E_C"
workers_dev = true


[vars]
AIRTABLE_BASE_ID = "tblLNDX7dDnOTZYy0"
AIRTABLE_TABLE_NAME = "test_project"
FORM_URL = "https://airtable.com/invite/r/reaVwXjP"
